service: cep-promise-service

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 128

package:
  exclude:
    - event.json

functions:
  cep:
    handler: handler.get
    events:
      - http:
          path: cep
          method: get